apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::992382613070:role/cert-manager-acme
  name: cert-manager
  namespace: cert-manager