apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: francis4fnc@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsZones:
          - "fnc.dns-dynamic.net"
      dns01:
        route53:
          region: us-west-1
          role: "arn:aws:iam::992382613070:role/cert-manager" # This must be set so cert-manager what role to attempt to authenticate with
          auth:
            kubernetes:
              serviceAccountRef:
                name: "cert-manager" # The name of the service account created